workflows:
  build-mobile:
    name: Build MAUI Android & iOS
    environment:
      vars:
        DOTNET_VERSION: "8.0.x"
    scripts:
      # Build Android APK
      - name: Build Android APK
        script: |
          dotnet publish Practica_Eco727/Practica_Eco727.csproj -f net8.0-android -c Release -o output/android

      # Build iOS IPA (requiere Mac runner y certificados)
      # - name: Build iOS IPA
      #   script: |
      #     dotnet publish Practica_Eco727/Practica_Eco727.csproj -f net8.0-ios -c Release -o output/ios

    artifacts:
      - output/android/**/*.apk
      # - output/ios/**/*.ipa
