workflows:
  build-mobile:
    name: Build MAUI Android & iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        DOTNET_VERSION: "8.0.x"
        DOTNET_PATH: $HOME/.dotnet
        DOTNET: $DOTNET_PATH/dotnet
    scripts:
      - name: Install .NET SDK
        script: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION --install-dir $DOTNET_PATH
          export PATH=$DOTNET_PATH:$PATH
          $DOTNET --version

      - name: Install MAUI workload
        script: |
          $DOTNET workload install android maui
          # Si también fuera iOS:
          # $DOTNET workload install ios maui

      - name: Build Android APK
        script: |
          $DOTNET publish Practica_Eco727/Practica_Eco727.csproj -f net8.0-android -c Release -o output/android

      # - name: Build iOS IPA
      #   script: |
      #     $DOTNET publish Practica_Eco727/Practica_Eco727.csproj -f net8.0-ios -c Release -o output/ios

    artifacts:
      - output/android/**/*.apk
      # - output/ios/**/*.ipa
